%% Generated by the Erlang ASN.1 compiler version:3.0.3
%% Purpose: Erlang record definitions for each named and unnamed
%% SEQUENCE and SET, and macro definitions for each value
%% definition,in module Ber



-ifndef(_BER_HRL_).
-define(_BER_HRL_, true).

-record('Message',{
peer, checksum, message}).

-endif. %% _BER_HRL_
